//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Common {
    using System.Xml.Serialization;
        
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:conditions:delegation")]
    [System.Xml.Serialization.XmlRootAttribute("Delegate", Namespace="urn:oasis:names:tc:SAML:2.0:conditions:delegation", IsNullable=false)]
    public partial class DelegateType {
        
        private object itemField;
        
        private System.DateTime delegationInstantField;
        
        private bool delegationInstantFieldSpecified;
        
        private string confirmationMethodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BaseID", typeof(BaseIDAbstractType), Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
        [System.Xml.Serialization.XmlElementAttribute("EncryptedID", typeof(EncryptedElementType), Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
        [System.Xml.Serialization.XmlElementAttribute("NameID", typeof(NameIDType), Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DelegationInstant {
            get {
                return this.delegationInstantField;
            }
            set {
                this.delegationInstantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelegationInstantSpecified {
            get {
                return this.delegationInstantFieldSpecified;
            }
            set {
                this.delegationInstantFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ConfirmationMethod {
            get {
                return this.confirmationMethodField;
            }
            set {
                this.confirmationMethodField = value;
            }
        }
    }
    
        
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:conditions:delegation")]
    public partial class DelegationRestrictionType : ConditionAbstractType {
        
        private DelegateType[] delegateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Delegate")]
        public DelegateType[] Delegate {
            get {
                return this.delegateField;
            }
            set {
                this.delegateField = value;
            }
        }
    }   
}
